// register actions
export const REGISTER_USER = "REGISTER_USER";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR";

// login actions
export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";

// auth user CRUD actions
export const SET_USER = "SET_USER";
export const UPDATE_USER = "UPDATE_USER";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_ERROR = "UPDATE_USER_ERROR";

// user actions
export const GET_USERS_WITH_MOST_ANSWERS = "GET_USERS_WITH_MOST_ANSWERS";
export const GET_USERS_WITH_MOST_ANSWERS_SUCCESS = "GET_USERS_WITH_MOST_ANSWERS_SUCCESS";

// questions CRUD actions
export const GET_QUESTIONS = "GET_QUESTIONS";
export const GET_LATEST_QUESTIONS = "GET_LATEST_QUESTIONS";
export const GET_HOT_QUESTIONS = "GET_HOT_QUESTIONS";
export const GET_MY_QUESTIONS = "GET_MY_QUESTIONS";
export const GET_QUESTIONS_SUCCESS = "GET_QUESTIONS_SUCCESS";
export const GET_LATEST_QUESTIONS_SUCCESS = "GET_LATEST_QUESTIONS_SUCCESS";
export const GET_HOT_QUESTIONS_SUCCESS = "GET_HOT_QUESTIONS_SUCCESS";
export const GET_MY_QUESTIONS_SUCCESS = "GET_MY_QUESTIONS_SUCCESS";
export const GET_QUESTIONS_ERROR = "GET_QUESTIONS_ERROR";
export const CREATE_QUESTION = "CREATE_QUESTION";
export const CREATE_QUESTION_SUCCESS = "CREATE_QUESTION_SUCCESS";
export const CREATE_QUESTION_ERROR = "CREATE_QUESTION_ERROR";
export const UPDATE_QUESTION = "UPDATE_QUESTION";
export const UPDATE_QUESTION_SUCCESS = "UPDATE_QUESTION_SUCCESS";
export const UPDATE_QUESTION_ERROR = "UPDATE_QUESTION_ERROR";
export const DELETE_QUESTION = "DELETE_QUESTION";
export const DELETE_QUESTION_SUCCESS = "DELETE_QUESTION_SUCCESS";
export const DELETE_QUESTION_ERROR = "DELETE_QUESTION_ERROR";

// answers CRUD actions
export const CREATE_ANSWER = "CREATE_ANSWER";
export const CREATE_ANSWER_SUCCESS = "CREATE_ANSWER_SUCCESS";
export const CREATE_ANSWER_ERROR = "CREATE_ANSWER_ERROR";
export const UPDATE_ANSWER = "UPDATE_ANSWER";
export const UPDATE_ANSWER_SUCCESS = "UPDATE_ANSWER_SUCCESS";
export const UPDATE_ANSWER_ERROR = "UPDATE_ANSWER_ERROR";
export const DELETE_ANSWER = "DELETE_ANSWER";
export const DELETE_ANSWER_SUCCESS = "DELETE_ANSWER_SUCCESS";
export const DELETE_ANSWER_ERROR = "DELETE_ANSWER_ERROR";

// notifications
export const GET_NOTIFICATIONS = "GET_NOTIFICATIONS";
export const GET_NOTIFICATIONS_SUCCESS = "GET_NOTIFICATIONS_SUCCESS";
export const MARK_NOTIFICATION_AS_CHECKED = "MARK_NOTIFICATION_AS_CHECKED";
export const MARK_NOTIFICATION_AS_CHECKED_SUCCESS = "MARK_NOTIFICATION_AS_CHECKED_SUCCESS";

